Initial build & Testing environment setup
distributed-technologies/mukube pull request #1
Opened 2021-03-10 18:01 UTC by skovbakke

The initial build and testing framework has ben configured. 

- The development environment is set up to make it easy to build the image and run the tests. 
- The image builds by running `make` which triggers the buildroot download and the build process.
- The tests framework has been set up and the initial tests work.

2021-03-10 18:10 UTC, skovbakke commented
There is still one glaring issue, which is that the ping test still fails. So far it seems that the issue lies with the VM manager which has not set up the propper networking. I hope to figure this out tomorrow.

2021-03-11 16:11 UTC, jacobcrawford reviewed
It is not clear how to run the project.

2021-03-11 16:11 UTC, jacobcrawford commented on README.md
> +To build the rootfs.iso simply run `make` from the main folder. This fetches the Buildroot toolchain and builds the iso.
I cannot run the project simply by pulling and running **make**.
Are we only suppose to run it through a container development environment?

2021-03-12 06:52 UTC, skovbakke commented on README.md
> +To build the rootfs.iso simply run `make` from the main folder. This fetches the Buildroot toolchain and builds the iso.
The container is a development environment for VSCode, so yes ideally you would run it by opening the containerized development environment in VSCode. 

It is also possible to build the container, sign in as the vscode user, as you describe, and build the image.

2021-03-12 06:56 UTC, skovbakke commented on README.md
> +To build the rootfs.iso simply run `make` from the main folder. This fetches the Buildroot toolchain and builds the iso.
> I mount the repo directory into `HOME` in the container.

You should mount the directory into the `home` folder. The `home` folder is owned by root, and regular users can not access it. You should mount it to a location where the `vscode` user has priviledges, e.g. /home/vscode/ or create a new folder `/workspace/` and change its permissions using `chmod`.

2021-03-12 06:59 UTC, jacobcrawford commented on README.md
> +To build the rootfs.iso simply run `make` from the main folder. This fetches the Buildroot toolchain and builds the iso.
Makes sence!
Can you update the docs on how to run the docker development locally?

2021-03-12 09:07 UTC, jaxels10 commented on README.md
> +To build the rootfs.iso simply run `make` from the main folder. This fetches the Buildroot toolchain and builds the iso.
@skovbakke

2021-03-12 09:14 UTC, skovbakke commented on README.md
> +To build the rootfs.iso simply run `make` from the main folder. This fetches the Buildroot toolchain and builds the iso.
I think it should work as follows: 
 - Build the docker container.
 - Run the docker container interactively.
 - As the vscode user go to the $HOME folder.
 - Clone the repository.
 - run `make`

2021-03-12 09:26 UTC, jaxels10 commented on config
> +# BR2_PACKAGE_LVM2 is not set
I don't know if this is something we need to think about right now, but Ceph needs LVM2 as far as I have understood it. https://rook.io/docs/rook/v1.5/ceph-prerequisites.html

2021-03-12 09:26 UTC, jaxels10 commented on testsuite/lib/mukube.exp
> +# We perform the setup and preparation of the virtual machine runnig the image.
running

2021-03-12 09:26 UTC, jaxels10 commented on testsuite/lib/mukube.exp
> +# Note that we wait for the prompt before issueing any command
issuing

2021-03-12 09:26 UTC, jaxels10 commented on testsuite/lib/mukube.exp
> +# Wait for the crng initialization to finish before continueing
continuing

2021-03-12 09:26 UTC, jaxels10 commented on testsuite/mukube-network.test/hostname.exp
> +# I need to read the correct hostname from the config files.
I think we generally try to avoid the word "I".

2021-03-12 09:50 UTC, skovbakke commented on config
> +# BR2_PACKAGE_LVM2 is not set
Alright, this will be relevant once we incorporate Ceph.

2021-03-12 10:01 UTC, skovbakke commented on testsuite/mukube-network.test/hostname.exp
> +# I need to read the correct hostname from the config files.
Yes, I have tried to do that generally. The above note was more of a note to myself.

2021-03-12 11:20 UTC, jacobcrawford commented on README.md
> +To build the rootfs.iso simply run `make` from the main folder. This fetches the Buildroot toolchain and builds the iso.
The process is cumbersome, and breaks with Martins request on "being able to clone the repository and run make"

Why dont we embed the code into the Dockerfile instead of cloning two times?

Then "make" could just:
1. Build image
2. Run the container with the "make" command and a mounted volume to the "artifacts" folder
3. Output to the "artifacts" folder

2021-03-12 11:20 UTC, jacobcrawford commented on README.md
> +To build the rootfs.iso simply run `make` from the main folder. This fetches the Buildroot toolchain and builds the iso.
@skovbakke

2021-03-12 11:33 UTC, skovbakke commented on README.md
> +To build the rootfs.iso simply run `make` from the main folder. This fetches the Buildroot toolchain and builds the iso.
This morning Martin and I have discussed this extensively. We will be working towards a solution where we will use containers as development environments, this solution should also resolve TECH-265 which describes the problem from the data scientist viewpoint.  
I am working on a first step towards this solution. The workflow initially should be something like 
- Start a docker image from a provided Dockerfile. (Potentially the container will pull the github repo or you will have to do it manually) 
- Use VSCode remote-ssh to remote into the container. 
- Run make inside the container.

For now you have to do it manually. I would say that reorganizing the entire container build environment is outside the scope of this pull-request.

2021-03-12 11:38 UTC, skovbakke commented on README.md
> +To build the rootfs.iso simply run `make` from the main folder. This fetches the Buildroot toolchain and builds the iso.
In reality, it does not break with Martins request. 
If you were able to follow the steps explained in setup.md all works. The process i described above is a workaround.

2021-03-17 08:07 UTC, jacobcrawford requested changes
The building of mukube works!
When I run the tests I get an error that  ```/workspaces/mukube/output``` does not exist, which is correct. I think it would work if I created the workspace folder, but does this path need to be absolute?

2021-03-17 08:07 UTC, jacobcrawford commented on testsuite/lib/mukube.exp
> +    --cdrom /workspaces/mukube/output/rootfs.iso
When I run the tests i get the error:
![image](https://user-images.githubusercontent.com/22328547/111433922-317d2680-86ff-11eb-80a4-441b0c915832.png)

2021-03-18 15:18 UTC, skovbakke commented on testsuite/lib/mukube.exp
> +    --cdrom /workspaces/mukube/output/rootfs.iso
I had an issue making the relative path work. Basically, putting in `../../output/rootfs.iso` did not work. And i could not easily figure out what exactly the working directory was for the script.  Once I retrofit the container building in the next task it should not be an issue.

2021-03-19 05:56 UTC, MartinSchmidt reviewed
I have left a few comments you can look through, and we can have a discussion in the developer group on the dev environments.

2021-03-19 05:56 UTC, MartinSchmidt commented on testsuite/config/unix.exp
> +
Empty file, is it required?

2021-03-19 05:56 UTC, MartinSchmidt commented on testsuite/lib/mukube.exp
> +    --cdrom /workspaces/mukube/output/rootfs.iso
My best guess would be that you started it in the `./testsuite` folder so maybe a single layer out `../output/rootfs.iso` works, if they have no documentation on how to do it then absolut paths can be the last resort.

2021-03-19 05:56 UTC, MartinSchmidt commented on README.md
> +To build the rootfs.iso simply run `make` from the main folder. This fetches the Buildroot toolchain and builds the iso.
I think we should have a continued discussion on the topic. A possible middle ground that can enable both flows would be to extract all dependencies from the .devcontainer Dockerfile into a `apt_requirement.txt` or similar, this can then be referenced and installed in the .devcontainer. Then we could atleast allow people to install the requirements locally and build the project. 

But it all boils into one question, what requirement do we put on the person who wants to run it? linux? Docker? devcontainers? Since @skovbakke  solution requires me to use **.devcontainers** but @jacobcrawford requires that I am on a linux with both **make** and **docker** installed. But lets have a longer discussion on teams on the issue.

2021-03-19 07:46 UTC, skovbakke commented on README.md
> +To run the accompanying tests go to the `testsuite` directory and run the command `runtest`.
`runtest` is the convention DejaGnu uses. We can also have a `make test` which would look like 
```
test : 
    cd testsuite && runtest
```

The question is what our standard is. I know we have talked about `make test` in an abstract sense, but since it is not implemented anywhere else I have not done it here either.

2021-03-19 07:49 UTC, skovbakke commented on testsuite/config/unix.exp
> +
It is not required. But it is recommended. 
If we do not have the file, `runtest` gives us a warning, because we have not specified a `board`, and opts to use a default `unix.exp`. I have not looked into what this default is exactly. The tests work either way.

2021-03-19 10:24 UTC, skovbakke commented
I have added documentation for launching the dev container without the use of *VSCode: Remote - Containers* extension. This should resolve the issues @jacobcrawford was having with getting the code to run.

2021-03-19 10:28 UTC, skovbakke commented on testsuite/lib/mukube.exp
> +    --cdrom /workspaces/mukube/output/rootfs.iso
If the container is launched according to the new documentation added in https://github.com/distributed-technologies/mukube/pull/1/commits/d198e2cbc34fbc78c7533afcbbe653c25885eadd this does not matter.

2021-03-19 10:35 UTC, skovbakke commented on README.md
> +To build the rootfs.iso simply run `make` from the main folder. This fetches the Buildroot toolchain and builds the iso.
@jacobcrawford I have added new documentation on how to launch the container https://github.com/distributed-technologies/mukube/pull/1/commits/d198e2cbc34fbc78c7533afcbbe653c25885eadd. The explanation i gave above is not a good way. 

@MartinSchmidt: Putting the package dependencies in a separate file, eg. `apt_requirement.txt` is possible, but if we do this Docker will no longer register changes in the dependencies. After any change you would have to rebuild without cache, which could take a long time.  
I have changed the documentation, and now it describes three equivalent ways of starting the development environment. This way we are not tied to one specific way of doing it. 

Hopefully, this will suffice for now.

2021-03-22 09:09 UTC, MartinSchmidt approved these changes

2021-03-22 12:49 UTC, merged