Feature/runtime testing
distributed-technologies/mukube pull request #10
Opened 2021-08-23 08:25 UTC by jacobcrawford

We setup runtime tests for the OS. The test ensures that a kubernetes cluster can boot.
A few changes have been made to make the test run successfully: 
1. The init script has been removed and the default system init is used
2.  /var/ is mounted as a tmpfs to make room for loading the containers
3.

2021-08-23 09:16 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/k8s-configuration.bb
> +	docker pull $image
```suggestion
        docker pull $image
```

2021-08-23 09:16 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/fstab
> +# stock fstab - you probably want to override this with a machine specific one
Why do we need a custom fstab file?

2021-08-23 09:16 UTC, klausenbusk commented on kas-test.yaml
> -    EXTRA_USERS_PARAMS = "usermod -P root root;"
So we can't login anymore?

2021-08-24 09:00 UTC, jacobcrawford commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/fstab
> +# stock fstab - you probably want to override this with a machine specific one
To make /var/ a tmpfs. This might be a temporary solution, but it is needed for the tests to run as /var/ is mounted in root otherwise which makes the folder fun out of memory when pulling images.

2021-08-24 09:02 UTC, jacobcrawford commented on kas-test.yaml
> -    EXTRA_USERS_PARAMS = "usermod -P root root;"
We should not be able to login to the production image. If we want a development image we will need to define this.
The development image can inherit the base production image and add features like root login and ssh server.

2021-08-24 09:02 UTC, jacobcrawford commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/fstab
> +# stock fstab - you probably want to override this with a machine specific one
Do you have a sugestion to solve the problem other than defining fstab?

2021-08-24 09:08 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/fstab
> +# stock fstab - you probably want to override this with a machine specific one
https://github.com/distributed-technologies/mukube/pull/9 should achieve the same. The rootfs is copied to memory and the memory pages are compressed. Perhaps we should merge it before this PR?

How much storage do you need for the images?

2021-08-24 09:10 UTC, klausenbusk commented on kas-test.yaml
> -    EXTRA_USERS_PARAMS = "usermod -P root root;"
I think we should either postpone the removal or add a dev image right away. I at least need shell access in the short term.

2021-08-24 14:21 UTC, skovbakke commented on README.md
> +To clean the test cuild run:
```suggestion
To clean the test build run:
```

2021-08-25 05:48 UTC, jacobcrawford commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/fstab
> +# stock fstab - you probably want to override this with a machine specific one
When I boot the image in #9 I get this:
![image](https://user-images.githubusercontent.com/22328547/130732202-2ddf26bb-247e-4496-a9c3-7b7137d44d69.png)
When I pull the images or extract the tarballs I get: 
![image](https://user-images.githubusercontent.com/22328547/130733157-7e51cfb7-4496-4310-b309-83caf57faa2c.png)
Telling the os to mount /var/ as a tmpfs fixes this issue.

2021-08-25 06:54 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/fstab
> +# stock fstab - you probably want to override this with a machine specific one
Booting the iso, I get this:
```sh
root@genericx86-64:~# df -h
Filesystem                Size      Used Available Use% Mounted on
devtmpfs                  2.8G      4.0K      2.8G   0% /dev
/dev/zram0                5.0G    644.6M      4.1G  13% /
tmpfs                     2.8G         0      2.8G   0% /dev/shm
tmpfs                     1.1G      8.5M      1.1G   1% /run
tmpfs                     4.0M         0      4.0M   0% /sys/fs/cgroup
tmpfs                     2.8G         0      2.8G   0% /tmp
tmpfs                     2.8G     12.0K      2.8G   0% /var/volatile
```

I will debug why booting the kernel/initrd directly work differently.

2021-08-25 07:12 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/fstab
> +# stock fstab - you probably want to override this with a machine specific one
We should just use `runqemu iso` for the future, using just `runqemu` it doesn't use the initrd at all.

2021-08-25 08:59 UTC, skovbakke reviewed
does not look too bad

2021-08-25 09:09 UTC, skovbakke requested changes

2021-08-25 09:09 UTC, skovbakke commented on README.md
> +`bitbake qemu-helper-native && bitbake mukube-test-image -c testimage `
Running the tests does not work. The above command gives me: 
```
ERROR: Task do_testimage does not exist for target mukube-test-image (~/yocto/mukube/meta-k8s-setup/recipes-mukube/images/mukube-test-image.bb:do_testimage). Close matches:
  do_image
ERROR: Command execution failed: 1
```

2021-08-25 09:40 UTC, jacobcrawford commented on kas-test.yaml
> -    EXTRA_USERS_PARAMS = "usermod -P root root;"
i have created an image "mukube-dev" that should be used for development purposes.

2021-08-25 09:41 UTC, jacobcrawford commented on README.md
> +`bitbake qemu-helper-native && bitbake mukube-test-image -c testimage `
Variables were incorrectly deleted from the testing kas file.

2021-09-01 07:48 UTC, skovbakke requested changes
A few things that could be changed

2021-09-01 07:48 UTC, skovbakke commented on kas-testing.yaml
> +    QB_DEFAULT_FSTYPE = "wic"
I think this should be moved to the base image. We only build `wic` images, right @klausenbusk ?

2021-09-01 07:48 UTC, skovbakke commented on .gitignore
> +**/**/__pycache__
```suggestion
**/__pycache__
```
This should have the same effect.

2021-09-01 07:48 UTC, skovbakke commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/k8s-configuration.bb
The summary needs to be updated. We use CRIO now.

2021-09-01 07:48 UTC, skovbakke commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/k8s-configuration.bb
> +    for image in $(echo ${CONTAINER_IMAGES}); do
I do not think `echo` is necessary here. `$CONTAINER_IMAGES` is already a list.

2021-09-01 07:48 UTC, skovbakke commented on meta-k8s-setup/recipes-mukube/images/mukube-test-image.bb
> +# Make qemu boot the iso to do testing
We no longer use an `iso`.

2021-09-01 12:31 UTC, skovbakke approved these changes
LGTM

2021-09-01 12:43 UTC, merged