Feature/config partition
distributed-technologies/mukube pull request #16
Opened 2021-09-02 11:26 UTC by jacobcrawford

Mounting a configuration partition in the /config folder.
 
Testing that we can create a ext4 fs with a tar, mount it into the /config folder using fstab and unpack it with a system unit file.

2021-09-06 12:59 UTC, klausenbusk requested changes

2021-09-06 12:59 UTC, klausenbusk commented on kas-testing.yaml
> +    HOSTTOOLS += "mkfs.ext4"
Let's try avoiding using host tools. Try using `DEPENDS = "e2fsprogs-native"` in k8s-testing.bb.

2021-09-06 12:59 UTC, klausenbusk commented on meta-k8s-setup/lib/oeqa/runtime/cases/config.py
> +        self.assertEqual(status, 0, msg=output)
Shelling out for this is a bit weird. Try something like this:
```suggestion
        self.assertTrue(os.path.exists("/config/config.tar.gz"))
```

2021-09-06 12:59 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/k8s-configuration.service
> +
No reason for all this:
```suggestion
Type=oneshot
```

2021-09-06 12:59 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/k8s-configuration.service
> +After=config.mount
```suggestion
Before=sysinit.target
```
We don't want `After=config.mount`, but if we did `RequiresMountsFor=/config` is the way to do it.
We also want this service to start before "normal services" like `crio.service` and `kubelet.service`, so add ``Before=sysinit.target` (I'm unsure if that will work tho).

2021-09-06 12:59 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/k8s-configuration.bb
> +    install -m 0755 ${WORKDIR}/fstab ${D}/etc/fstab
```suggestion
    install -m 0644 ${WORKDIR}/fstab ${D}/etc/fstab
```

2021-09-06 12:59 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/k8s-configuration.bb
> +    install -m 0755 ${WORKDIR}/k8s-configuration.service ${D}/etc/systemd/system/k8s-configuration.service
```suggestion
    install -m 0644 ${WORKDIR}/k8s-configuration.service ${D}/etc/systemd/system/k8s-configuration.service
```

2021-09-06 12:59 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-testing/k8s-testing/k8s-testing.bb
> +LIC_FILES_CHKSUM = "file://${WORKDIR}/COPYING.MIT;md5=3da9cfbcb788c80a0384361b4de20420"
```suggestion
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"
```

2021-09-06 12:59 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-testing/k8s-testing/files/COPYING.MIT
> +Permission is hereby granted, free of charge, to any person obtaining a copy
Delete this file. See suggestion to `k8s-testing.bb`.

2021-09-06 12:59 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/k8s-configuration.service
> +WantedBy=multi-user.target
```suggestion
```
We don't want it to be installable, it should be pulled in by the mount unit.

2021-09-06 12:59 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/crio.service
> +Wants=network.target k8s-configuration.service
```suggestion
Wants=network.target
```
Let's not do this. `k8s-configuration.service` shouldn't be pulled in by some "random" service. Let's pull it in with the mount unit.

2021-09-06 12:59 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/crio.service
> +After=network.target k8s-configuration.service
```suggestion
After=network.target
```

2021-09-06 12:59 UTC, klausenbusk commented on meta-k8s-setup/recipes-mukube/images/mukube-test-image.bb
> +MK_CONFIG_FILE_PATH = "${BASE_WORKDIR}/core2-64-poky-linux/k8s-testing/1.0-r0/temp/config.ext4"
Hmm, we should be able to use use `IMGDEPLOYDIR` by `inherit image` in `k8s-testing.bb`.

2021-09-06 12:59 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/fstab
> +LABEL=config         /config              ext4       defaults              0  0
```suggestion
LABEL=config         /config              ext4       defaults,x-systemd.requires=k8s-configuration.service,x-systemd.before=k8s-configuration.service              0  0
```
Let's pull in the service here.

2021-09-06 13:14 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/k8s-configuration.service
> +After=config.mount
This will not work, try:
```suggestion
DefaultDependencies=no
Conflicts=shutdown.target
After=local-fs.target
Before=sysinit.target shutdown.target
```
or we could just 
```suggestion
Before=multi-user.target
```
but then it would be starting a bit later (but still early enough), hmm🤔

See https://www.freedesktop.org/software/systemd/man/bootup.html#System%20Manager%20Bootup for the boot process.

2021-09-06 13:38 UTC, jacobcrawford commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/k8s-configuration.service
> +After=config.mount
Well we need to make sure that the service is not started before the config partition is mounted, so how do we do that if not with: After=config.mount

2021-09-06 15:05 UTC, jacobcrawford commented on meta-k8s-setup/lib/oeqa/runtime/cases/config.py
> +        self.assertEqual(status, 0, msg=output)
Well the command does not work when using it in the tests.

2021-09-06 15:44 UTC, klausenbusk commented on meta-k8s-setup/lib/oeqa/runtime/cases/config.py
> +        self.assertEqual(status, 0, msg=output)
Hmm, make sense, a bit limiting tho.

2021-09-07 09:03 UTC, jacobcrawford commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/files/k8s-configuration.service
> +After=config.mount
We enable the service with the Yocto systemd class

2021-09-07 09:19 UTC, jacobcrawford commented on meta-k8s-setup/recipes-mukube/images/mukube-test-image.bb
> +MK_CONFIG_FILE_PATH = "${BASE_WORKDIR}/core2-64-poky-linux/k8s-testing/1.0-r0/temp/config.ext4"
Since k8s-testing is a recipe that is not an image, we get permission denied, when trying to modify the IMGDEPLOYDIR directory.

2021-09-07 09:51 UTC, klausenbusk commented on meta-k8s-setup/recipes-k8s-configuration/k8s-configuration/k8s-configuration.bb
> +SYSTEMD_SERVICE_k8s-configuration = "k8s-configuration.service"
```suggestion
SYSTEMD_AUTO_ENABLE:${PN} = "enable"
SYSTEMD_SERVICE:${PN} = "k8s-configuration.service"
```

2021-09-07 10:29 UTC, klausenbusk commented on meta-k8s-setup/recipes-mukube/images/mukube-test-image.bb
> +MK_CONFIG_FILE_PATH = "${BASE_WORKDIR}/core2-64-poky-linux/k8s-testing/1.0-r0/temp/config.ext4"
Maybe it should be a image, but good enough for now.

2021-09-07 10:30 UTC, klausenbusk commented on meta-k8s-setup/wic/mukube.wks.in
> +part /config --source rawcopy --sourceparams="file=${MK_CONFIG_FILE_PATH}" --part-type 0FC63DAF-8483-4772-8E79-3D69D8477DE4 --label config --fstype ext4
```suggestion
part /config --source rawcopy --sourceparams="file=${MK_CONFIG_FILE_PATH}" --part-type 0FC63DAF-8483-4772-8E79-3D69D8477DE4 --label config --fstype ext4 --align 1024
```
It should be alligned.

2021-09-07 12:53 UTC, klausenbusk approved these changes
LGTM 🎉

2021-09-07 12:53 UTC, merged

2021-09-09 12:49 UTC, skovbakke commented
There is an issue. The only target that can build is `mukube-test-image`. The others do not set the `MK_CONFIG_FILE_PATH` variable and they also do not generate `config.ext4` to use in the config partition.