Feature/multi config
distributed-technologies/mukube pull request #28
Opened 2021-09-16 13:46 UTC by skovbakke

Added target for building multiple `.wic` files for an entire cluster. This is a temporary solution in order to combine our yocto setup with the configurations in the mukube-configurator.

2021-09-17 08:08 UTC, jacobcrawford requested changes
Nothing much. Looks good.

2021-09-17 08:08 UTC, jacobcrawford commented on meta-k8s-setup/recipes-k8s-testing/k8s-testing/k8s-testing.bb
> +
Fix line indents in do_compile

2021-09-17 08:15 UTC, skovbakke commented on meta-k8s-cluster/recipes-mukube/images/mukube-cluster-image.bb
> +			# do_image_wic execution
It is present in the `IMAGE_CMD_wic` command, so i assume it is a good thing to do. I believe interrupt means `^C` to stop the execution.

2021-09-17 11:04 UTC, skovbakke commented
Tests pass 
```
NOTE: Executing Tasks
RESULTS:
RESULTS - config.ConfigPartitionTest.test_config_present: PASSED (0.25s)
RESULTS - kubeadm.KubeadmInitTest.test_kubeadm_init: PASSED (71.94s)
SUMMARY:
mukube-test-image () - Ran 2 tests in 72.191s
mukube-test-image - OK - All required tests passed (successes=2, skipped=0, failures=0, errors=0)
NOTE: Tasks Summary: Attempted 310 tasks of which 308 didn't need to be rerun and all succeeded.
```

2021-09-20 07:59 UTC, klausenbusk commented
Let's get https://github.com/distributed-technologies/mukube/pull/27 in first.

2021-09-20 09:51 UTC, skovbakke commented
#27 is now merged.

2021-09-20 13:03 UTC, jacobcrawford approved these changes
lgtm

2021-09-20 13:12 UTC, merged