Feature/swtpm support
distributed-technologies/mukube pull request #33
Opened 2021-09-23 13:52 UTC by skovbakke

Added a very basic script to start the `swtpm` as well as a patch to `meta-security` to update it.

2021-09-24 06:44 UTC, klausenbusk requested changes
Please add the patches to [docs/patches.md](https://github.com/distributed-technologies/mukube/blob/feature/yocto-switch/docs/patches.md)

2021-09-24 07:29 UTC, klausenbusk commented on scripts/start-swtpm
> +$swtpm_oe socket --tpmstate dir=/tmp/mytpm1 --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock --log level=20 --tpm2
```suggestion
swtpm_oe="$(echo tmp/work/*/swtpm-wrappers-native/*/swtpm_oe.sh)"

if [ ! -f "$swtpm_oe" ] then
  echo "swtpm_oe.sh not found, exiting..."
  exit 1
fi

echo "Running ${swtpm_oe}"

mkdir -p /tmp/mytpm1
"$swtpm_oe" socket --tpmstate dir=/tmp/mytpm1 --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock --log level=20 --tpm2 
```

2021-09-24 09:16 UTC, jacobcrawford requested changes

2021-09-24 09:16 UTC, jacobcrawford commented on meta-k8s-setup/recipes-mukube/images/mukube-test-image.bb
> +require mukube-dev-image.bb
I don't think it is a good idea for us to make the test image depend on the dev image, instead of the production image. In this case, we can have a situation where we have added features or packages for development purposes, that will make the tests succeed. 
In general, we want to test a setup as similar to production as possible.

2021-09-24 09:36 UTC, skovbakke commented on meta-k8s-setup/recipes-mukube/images/mukube-test-image.bb
> +require mukube-dev-image.bb
I agree that we should test an image as close to the production image as possible. It just seemed that they were almost the same, and we had the same configurations in both of them.
Could we make a dependency the other way with the dev image depending on the test image?

2021-09-24 09:39 UTC, skovbakke commented on kas-base.yaml
> +      ../meta-security:
Not really a reason. I saw it in a kas file from meta-security [kas-security-base.yml](https://git.yoctoproject.org/cgit/cgit.cgi/meta-security/tree/kas/kas-security-base.yml)
Which do you prefer?

2021-09-24 11:58 UTC, jacobcrawford commented on meta-k8s-setup/recipes-mukube/images/mukube-test-image.bb
> +require mukube-dev-image.bb
yes, I think that way would make more sense. :)

2021-09-27 09:53 UTC, skovbakke commented
Test run automatically when the `mukube-test-image` target is built, and they pass:
```
NOTE: Executing Tasks
RESULTS:
RESULTS - config.ConfigPartitionTest.test_config_present: PASSED (0.33s)
RESULTS - kubeadm.KubeadmInitTest.test_kubeadm_init: PASSED (67.11s)
SUMMARY:
mukube-test-image () - Ran 2 tests in 67.445s
mukube-test-image - OK - All required tests passed (successes=2, skipped=0, failures=0, errors=0)
```

2021-09-27 11:10 UTC, klausenbusk requested changes

2021-09-27 11:10 UTC, klausenbusk commented on docs/patches.md
> +| [`0001-Update-swtpm-to-0.6.1-and-libtpms-to-0.8.7.patch`](../patches/meta-security/swtpm/0001-Update-swtpm-to-0.6.1-and-libtpms-to-0.8.7.patch) | [meta-security](https://git.yoctoproject.org/cgit/c
Nitpick, let's keep it lowercase as the rest:
```suggestion
| [`0001-Update-swtpm-to-0.6.1-and-libtpms-to-0.8.7.patch`](../patches/meta-security/swtpm/0001-Update-swtpm-to-0.6.1-and-libtpms-to-0.8.7.patch) | [meta-security](https://git.yoctoproject.org/cgit/cgit.cgi/meta-security/) | pending upstream submission | Updates the libtpms, swtpm, and the wrapper scripts to the newest version |
```

2021-09-27 11:10 UTC, klausenbusk commented on meta-k8s-setup/recipes-mukube/images/mukube-dev-image.bb
> +		"
Hmm, the indentation looks off?

2021-09-27 11:15 UTC, skovbakke commented on meta-k8s-setup/recipes-mukube/images/mukube-dev-image.bb
> +		"
yes!

2021-09-27 11:40 UTC, klausenbusk approved these changes
LGTM 🎉

2021-09-27 11:42 UTC, merged