Update of documentation
distributed-technologies/mukube pull request #35
Opened 2021-09-28 07:39 UTC by skovbakke

An update to the documentation as well as documentation of newly implemented features and design changes.

2021-09-28 09:59 UTC, klausenbusk requested changes

2021-09-28 09:59 UTC, klausenbusk commented on README.md
> +The aim of the project is to build a minimal linux distribution capable of runninb kubernetes and with support for needed security features. The project is based on [the yocto project](https://www.yo
```suggestion
The aim of the project is to build a minimal Linux distribution capable of running Kubernetes and with support for needed security features. The project is based on [the Yocto project](https://www.yoctoproject.org/) and [OpenEmbedded](http://www.openembedded.org/wiki/Main_Page), which uses [BitBake](https://www.yoctoproject.org/docs/latest/bitbake-user-manual/bitbake-user-manual.html) as the task execution engine. On top of that we use [kas](https://kas.readthedocs.io/en/latest/userguide.html#usage) to manage the project dependencies and build the project.
```

2021-09-28 09:59 UTC, klausenbusk commented on README.md
> +* Install have [kas](https://kas.readthedocs.io/en/latest/userguide.html) available and create a `kas-local.yaml`
```suggestion
* Install [`kas`](https://kas.readthedocs.io/en/latest/userguide.html#dependencies-installation) and create a `kas-local.yaml` file
```

2021-09-28 09:59 UTC, klausenbusk commented on README.md
> +	version: 10
```suggestion
  version: 10
```

2021-09-28 09:59 UTC, klausenbusk commented on README.md
> +To use the nfs server, the exposed directories must be mounted on the machine you are working on.
```suggestion
To use a NFS server, the exposed directories must be mounted on the machine you are working on. 
```

2021-09-28 09:59 UTC, klausenbusk commented on README.md
> +2. add the following line to `/etc/fstab` in order to mount the nfs at boot `<ip_of_nfs-server>:/	/mnt	nfs	auto	0	0`
```suggestion
1. Install the package `nfs-common` using eg. `apt`
2. Add the following line to `/etc/fstab` in order to mount the NFS at boot `<ip_of_nfs-server>:/	/mnt	nfs	auto	0	0` 
```

2021-09-28 09:59 UTC, klausenbusk commented on README.md
> +## Building and Testing using kas/bitbake
```suggestion
## Building and testing using kas/bitbake 
```

2021-09-28 09:59 UTC, klausenbusk commented on README.md
> +We have a few tests we run with the image. They are implemented in python are located in [cases](meta-k8s-setup/lib/oeqa/runtime/cases). Our test image is configured for the tests to run automaticall
```suggestion
We have a few tests we run with the image. They are implemented in Python and are located in [`meta-k8s-setup/lib/oeqa/runtime/cases`](meta-k8s-setup/lib/oeqa/runtime/cases). Our test image is configured for the tests to run automatically when the target is built. Thus to run the tests, simply build the test target, with either `kas build mukube/kas-testing.yaml` or from the kas shell run `bitbake mukube-test-image`.
```

2021-09-28 09:59 UTC, klausenbusk commented on docs/design.md
> +## Sedure Boot
```suggestion
## Secure Boot
```

2021-09-28 09:59 UTC, klausenbusk commented on README.md
> +Notice that the swtpm exits when the virtual machine turns off, and has to be relaunched before the next use.
```suggestion
Notice that swtpm exits when the virtual machine turns off, and has to be relaunched before the next use.
```

2021-09-30 15:44 UTC, skovbakke commented
Did an almost full rewrite of the README page and included documentation of components of the boot process.

2021-10-04 07:11 UTC, klausenbusk commented on docs/image.md
> +In order to simplify the Secure Boot process and have everything signed, we package the kernel, initrd, and the kernel command line in a [unified kernel image](https://systemd.io/BOOT_LOADER_SPECIFIC
```suggestion
In order to simplify the Secure Boot process and have everything signed, we package the kernel, initrd, and the kernel command line in a [Unified Kernel Image](https://systemd.io/BOOT_LOADER_SPECIFICATION#type-2-efi-unified-kernel-images). Booting this is supported with the bootloader [systemd-boot](https://www.freedesktop.org/software/systemd/man/sd-boot.html).
```

2021-10-04 07:11 UTC, klausenbusk commented on docs/image.md
> +The image boots with UEFI Secure Boot. In a virtual environment UEFI is supported through ovmf ([open virtual machine firmware](https://www.linux-kvm.org/page/OVMF)).
```suggestion
The image boots with UEFI Secure Boot. In a virtual environment UEFI is supported through OVMF ([Open Virtual Machine Firmware](https://www.linux-kvm.org/page/OVMF)). 
```

2021-10-04 13:05 UTC, jacobcrawford requested changes
A few comments. looks good.

2021-10-04 13:05 UTC, jacobcrawford commented on README.md
> +We have a few tests we run with the image. They are implemented in Python and are located in [`meta-k8s-setup/lib/oeqa/runtime/cases`](meta-k8s-setup/lib/oeqa/runtime/cases). Our test image is config
Have we actually made it so that the tests run on build? I did not enable the feature when I wrote the tests.

2021-10-04 14:21 UTC, skovbakke commented on README.md
> +We have a few tests we run with the image. They are implemented in Python and are located in [`meta-k8s-setup/lib/oeqa/runtime/cases`](meta-k8s-setup/lib/oeqa/runtime/cases). Our test image is config
Yes, It is enabled now. I did that a few PRs back.

2021-10-04 14:22 UTC, skovbakke commented on README.md
> +* [Design](docs/design.md)
You are correct. That is a mistake.

2021-10-05 05:30 UTC, jacobcrawford approved these changes
LGTM

2021-10-06 07:18 UTC, klausenbusk reviewed
LGTM 🎉

2021-10-06 07:18 UTC, klausenbusk approved these changes
LGTM 🎉

2021-10-06 07:18 UTC, merged