Feature/poky update
distributed-technologies/mukube pull request #60
Opened 2021-12-16 06:24 UTC by skovbakke

2021-12-16 10:42 UTC, klausenbusk commented on docs/patches.md
> +| [`0001-CRI-O-Update-to-1.22.1-and-fix-SRCREV-SRC_URI.patch`](../patches/meta-virtualization/misc/0001-CRI-O-Update-to-1.22.1-and-fix-SRCREV-SRC_URI.patch) | [meta-virtualization](https://git.yoctop
This sounds like something upstream should fix.

It is already [fixed in master](https://git.yoctoproject.org/meta-virtualization/commit/recipes-containers/cri-o/cri-o_git.bb?id=17e0be0dc3763bd7a92728b90087072c5afc59ea) so just a missing backport it seems.

Let me try to reach out to upstream.

2021-12-16 12:04 UTC, klausenbusk commented on docs/patches.md
> +| [`0001-CRI-O-Update-to-1.22.1-and-fix-SRCREV-SRC_URI.patch`](../patches/meta-virtualization/misc/0001-CRI-O-Update-to-1.22.1-and-fix-SRCREV-SRC_URI.patch) | [meta-virtualization](https://git.yoctop
Backport submitted: https://lists.yoctoproject.org/g/meta-virtualization/topic/honister_patch_cri_o/87765433

2021-12-17 07:08 UTC, klausenbusk commented on docs/patches.md
> +| [`0001-CRI-O-Update-to-1.22.1-and-fix-SRCREV-SRC_URI.patch`](../patches/meta-virtualization/misc/0001-CRI-O-Update-to-1.22.1-and-fix-SRCREV-SRC_URI.patch) | [meta-virtualization](https://git.yoctop
Cherry-picked: https://git.yoctoproject.org/meta-virtualization/commit/?h=honister&id=7618d5046a24e4c8852560b17f815b1ce3cba160

2021-12-17 09:56 UTC, klausenbusk commented on docs/patches.md
> +| [`0001-dm-verity-img.bbclass-Fix-the-override-fixups.patch`](../patches/meta-security/misc/0001-dm-verity-img.bbclass-Fix-the-override-fixups.patch) | [meta-security](https://git.yoctoproject.org/c
Submitted upstream: https://lists.yoctoproject.org/g/yocto/topic/meta_security_patch/87786381. I expect it to be backported.

2022-01-04 10:51 UTC, klausenbusk commented on docs/patches.md
> +| [`0001-dm-verity-img.bbclass-Fix-the-override-fixups.patch`](../patches/meta-security/misc/0001-dm-verity-img.bbclass-Fix-the-override-fixups.patch) | [meta-security](https://git.yoctoproject.org/c
Landed upstream: https://git.yoctoproject.org/meta-security/commit/?id=126860dac30d50a5894588b874ae917b0b310142, please cherry-pick.

2022-01-04 10:53 UTC, klausenbusk commented on docs/patches.md
> +| [`0001-CRI-O-Update-to-1.22.1-and-fix-SRCREV-SRC_URI.patch`](../patches/meta-virtualization/misc/0001-CRI-O-Update-to-1.22.1-and-fix-SRCREV-SRC_URI.patch) | [meta-virtualization](https://git.yoctop
Please remove the patch as it has been backported.

2022-01-24 09:51 UTC, klausenbusk commented on docs/patches.md
> +| [0001-dm-verity-img.bbclass-Fix-wrong-override-syntax-for-.patch](../patches/meta-security/misc/0001-dm-verity-img.bbclass-Fix-wrong-override-syntax-for-.patch) | [meta-security](https://git.yoctop
I have requested a backport: https://lists.yoctoproject.org/g/yocto/topic/honister_patch/88643459

2022-01-24 10:55 UTC, klausenbusk commented on docs/patches.md
> +| [`0001-CRI-O-Remove-containerd-as-RDEPENDS.patch`](../patches/meta-virtualization/misc/0001-CRI-O-Remove-containerd-as-RDEPENDS.patch) | [meta-virtualization](https://git.yoctoproject.org/cgit/cgit
Could this just be a `bbappend` file?

2022-01-24 11:57 UTC, jacobcrawford requested changes
Please paste a screenshot of a successful test run.

2022-01-24 12:07 UTC, jacobcrawford commented
Do we need to take into account the KubeletConfiguration generated in mukube-configurator?

2022-01-24 14:42 UTC, jacobcrawford commented
When building this on a fresh Debian I get:
 
![image](https://user-images.githubusercontent.com/22328547/150803940-51f28aa0-9a21-4da2-b4e4-220fc513251d.png)

If there are hosttools needed we should list these requirements.

2022-01-24 19:54 UTC, skovbakke commented
> When building this on a fresh Debian I get:
> 
> ![image](https://user-images.githubusercontent.com/22328547/150803940-51f28aa0-9a21-4da2-b4e4-220fc513251d.png)
> 
> If there are hosttools needed we should list these requirements.

Indeed. This is documented, [here](https://docs.yoctoproject.org/ref-manual/system-requirements.html#required-packages-for-the-build-host), as these are part of the requirements to using yocto.

2022-01-24 19:55 UTC, skovbakke commented
> Do we need to take into account the KubeletConfiguration generated in mukube-configurator?

No, that change does not affect anything here.

2022-01-24 20:16 UTC, skovbakke commented
All test are passing
![image](https://user-images.githubusercontent.com/78202835/150857713-78efe538-636f-4899-ae90-d99cd714da1a.png)

2022-01-25 05:38 UTC, skovbakke commented on docs/patches.md
> +| [`0001-CRI-O-Remove-containerd-as-RDEPENDS.patch`](../patches/meta-virtualization/misc/0001-CRI-O-Remove-containerd-as-RDEPENDS.patch) | [meta-virtualization](https://git.yoctoproject.org/cgit/cgit
Yes, that is a good idea.

2022-01-25 09:25 UTC, jacobcrawford commented
![image](https://user-images.githubusercontent.com/22328547/150949010-529f731d-d0df-40c9-b0ea-2abe4adc08ea.png)

Some recipes are not able to be fetched. What do we do when this happens?

2022-01-25 09:34 UTC, jacobcrawford commented
![image](https://user-images.githubusercontent.com/22328547/150950492-177d1305-e468-4e1f-bb39-9449e7235f4e.png)

2022-01-25 09:35 UTC, jacobcrawford commented
![image](https://user-images.githubusercontent.com/22328547/150950605-a1da52ca-4711-4171-a492-85576fc9ff0d.png)

2022-01-26 01:35 UTC, skovbakke commented
> ![image](https://user-images.githubusercontent.com/22328547/150949010-529f731d-d0df-40c9-b0ea-2abe4adc08ea.png)
> 
> Some recipes are not able to be fetched. What do we do when this happens?

We try to fix it. It turns out that the branch name has changed from `master` to `main`. So in order to fetch the source code we needed to specify that the branch is main (as master is the default).  The error did not show up for me, probably because the source was already fetched and/or the step/recipe was cached.

2022-01-26 12:32 UTC, jacobcrawford commented
If the master branch has changed name we should make the main branch the one we use.
setting
`SRC_URI = "git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git;protocol=https;branch=main"`
in meta-k8s-setup/recipes-core/microcode/amd-microcode_20210919.bb worked for me.

2022-01-26 12:34 UTC, jacobcrawford requested changes
If we update the branch for microcode to `main`, I think this is good to go :)

2022-01-26 17:48 UTC, klausenbusk approved these changes
LGTM 🎉

Tested with https://github.com/distributed-technologies/mukube-configurator/pull/42 with https://github.com/distributed-technologies/mukube-configurator/pull/43 and https://github.com/distributed-technologies/mukube-configurator/pull/44 on top.

2022-01-26 18:40 UTC, klausenbusk submitted a review, later dismissed
LGTM 🎉

Tested with https://github.com/distributed-technologies/mukube-configurator/pull/42 with https://github.com/distributed-technologies/mukube-configurator/pull/43 and https://github.com/distributed-technologies/mukube-configurator/pull/44 on top.

2022-01-27 06:37 UTC, jacobcrawford approved these changes
LGTM!

2022-01-27 07:30 UTC, klausenbusk approved these changes
LGTM 🎉

Tested with distributed-technologies/mukube-configurator#42 with distributed-technologies/mukube-configurator#43 and distributed-technologies/mukube-configurator#44 on top.

2022-01-27 08:00 UTC, merged